
//----------------------------------------------------
// The following code was generated by CUP v0.10a
// Wed Jul 24 21:44:00 EDT 1996
//----------------------------------------------------

package Parse;

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int FUNCTION = 42; // func
  static final int EOF = 0; // eof
  static final int INT = 4; // integer
  static final int GT = 23; // >
  static final int DIVIDE = 18; // /
  static final int COLON = 6; // :
  static final int ELSE = 31; // else
  static final int OR = 26; // |
  static final int NIL = 41; // nil
  static final int DO = 35; // do
  static final int GE = 24; // >=
  static final int error = 1; // err
  static final int LT = 21; // <
  static final int OF = 39; // of
  static final int MINUS = 16; // -
  static final int ARRAY = 28; // arr
  static final int TYPE = 44; // type
  static final int FOR = 33; // for
  static final int TO = 34; // to
  static final int TIMES = 17; // *
  static final int COMMA = 5; // ,
  static final int LE = 22; // <=
  static final int IN = 37; // in
  static final int END = 38; // end
  static final int ASSIGN = 27; // :=
  static final int STRING = 3; // ""
  static final int DOT = 14; // .
  static final int LPAREN = 8; // (
  static final int RPAREN = 9; // )
  static final int IF = 29; // if 
  static final int SEMICOLON = 7; // ;
  static final int ID = 2; // identifier
  static final int WHILE = 32; // while
  static final int LBRACK = 10; // {
  static final int RBRACK = 11; // }
  static final int NEQ = 20; // <>
  static final int VAR = 43; // var
  static final int BREAK = 40; // break
  static final int AND = 25; // &
  static final int PLUS = 15; // +
  static final int LBRACE = 12; // [
  static final int RBRACE = 13; // ]
  static final int LET = 36; // let
  static final int THEN = 30; // then
  static final int EQ = 19; // =
};
